apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: https://github.com/your-user/tax_calculator.git
    - name: revision
      value: main
    - name: image-reference
      value: us.icr.io/your-namespace/tax-calculator
    - name: app-name
      value: tax-calculator
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
